# Generated by Django 5.1 on 2024-08-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('students', '0002_alter_student_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('event_venue', models.CharField(max_length=200)),
                ('event_description', models.CharField(max_length=200)),
                ('event_logo', models.ImageField(blank=True, null=True, upload_to='event_logo/')),
                ('event_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=30)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.colleges')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(through='colleges.EventRegistration', to='students.student'),
        ),
    ]
