# Generated by Django 5.1 on 2024-10-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_rename_event_date_event_event_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_pdf',
            field=models.FileField(blank=True, null=True, upload_to='event_pdfs/'),
        ),
    ]
